### ISSUE TITLE
一键部署的问题

### ISSUE THREAD

**Issue by gmars** [TarsCloud/TarsDocs#34]
大佬们，一键部署的时候节点ip是直接从INET网卡上获取的。但是现在很多云服务器都是弹性ip是不可见的，能不能在这儿让大家输入ip地址而不是网卡名称呢？

chmod a+x linux-install.sh
./linux-install.sh MYSQL_HOST MYSQL_PASSWORD INET REBUILD(false[default]/true) SLAVE(false[default]/true) MYSQL_USER MYSQL_PORT

**Comment by ruanshudong** [comment]
一般还是绑定内网, 外网过来走网关之类的进来
